name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Cache install
        uses: actions/cache@v2
        with:
          path: ./node_modules/
          key: ${{ github.sha }}-install

  code_style:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Retrive install cache
        uses: actions/cache@v2
        with:
          path: ./node_modules/
          key: ${{ github.sha }}-install
      - name: prettier
        run: npm run prettier:check

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: Retrive Install Cache
        uses: actions/cache@v2
        with:
          path: ./node_modules/
          key: ${{ github.sha }}-install
      - name: Build
        run: npm run build
